cat <<EOF > csr_template.yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer-csr
spec:
  request: MIICWTCCAUECAQAwFDESMBAGA1UEAwwJZGV2ZWxvcGVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo4+DLcg191VbH8lSrC8PxJKmmLmB3bnvD7WvulkmtSsDw1/RLipQFkxHy84ot6D8ZjXptte0NyZfxENgCwMWTEnVkdZ/oVciUjfhs/dweicyBPwab32hpYXp3/UTNu+XV3Nye6brEh2F/yo68wDu9Wm1fNHQkMraq9Kz9MWf3iXigP1XZivqyUnG2htzFzANcIyP+0NoLCOWq7RZksztqa6xbWcjcBeDT1VQyMIiU98LO5ABC+Hbs9S9S1q9hBtz25ar9jhoQFthVduQU/n5xXAkqeAtjhVPiPVgruT4gnUaDQm3x3qHLsf6h1g6mstsxAqM2Q1Z+3rAuH6KGM2fzQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAGkOdZ5zYzUPM7ommlR6ltTHlp18PoEDqGb7d30QCe/0muT8mdt1g3mcwCh5HrzTqAwUqwOZ8kEvJcQDiW7Lkrk1rc9wy9XfTfSQSp18+5xxkamIpCHjewZkVi3mJwi/IcAt+5vTBmItCSR67/7qt5Kii8evPekloRQKgr6v/8D5AvK8IjyImmwAKZTQ867WTiKEEfM0e65etw+3OXzRK3vkipmyOJa8hBm/Rnbcrk0riKhWAcCmY1c/78llAL9mO2yetNMZn6V/4unZPYv/4+tQ5JttAp6jKZ/nylEqmxCAaX8Bal6dczXrcEVJA/I+BAMdQaiQHKl4vyDpjITg0MY=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
EOF
